local_api_funcs = {
    # 'lowes': 'lowes',
    # "northerntool":"northerntool",
    'motionindustries': 'motionindustries',
    # 'onesource': 'onesource',
    'accugroup': 'accugroup',
    'edmundoptics': 'edmundoptics',
    # 'knightoptical': 'knightoptical',
    # 'teconnectivity': 'teconnectivity',
    'biscoind': 'biscoind',
    # 'professionalplastics': 'professionalplastics',
    'supplyhouse': 'supplyhouse',
    # 'graybar': 'graybar',
    # 'iewc': 'iewc',
    # 'coleparmer': 'coleparmer',
    # 'tequipment': 'tequipment',
    # 'fastenal': 'fastenal',
    # 'mscdirect': 'mscdirect',
    # "galco":"galco"
}

aws_api_funcs = {
    'teconnectivity': 'teconnectivity',
    "northerntool":"northerntool",
    'fastenal': 'fastenal',
    # "ellsworthadhesives":"ellsworthadhesives",
    "harborfreight":"harborfreight",
    # 'nbk': 'nbk',
    'cdw': 'cdw',
    'wolfautomation': 'wolfautomation',
    'hisco': 'hisco',
    'globalindustrial': 'globalindustrial',
    'mrosupply': 'mrosupply',
    # 'autodir': 'autodir',
    # 'sdpsi': 'sdpsi',
    'fixsupply': 'fixsupply',
    # 'futek': 'futek',
    'omega': 'omega',
    'freshwatersystems': 'freshwatersystems',
    # 'mwcomponents': 'mwcomponents',
    'igus': 'igus',
    # 'usplastic': 'usplastic',
    'mscdirect': 'mscdirect',
    'reidsupply': 'reidsupply',
    'tacomascrew': 'tacomascrew',
    'testequity': 'testequity',
    # 'baslerweb': 'baslerweb',
    # 'asmcindustrial': 'asmcindustrial',
    # 'tacuna': 'tacuna',
    # 'meetoptics': 'meetoptics',
    # 'kjmagnetics': 'kjmagnetics',
    'skygeek': 'skygeek',
    'rockwestcomposites': 'rockwestcomposites',  
    # 'thermofisherscientific': 'thermofisherscientific',
    # 'eplastics': 'eplastics',
    # 'applied': 'applied',
    'metals4u': 'metals4u',
    'walkerindustrial': 'walkerindustrial',
    # 'trimantec': 'trimantec',
    # 'boltdepot': 'boltdepot',
    # 'thomasscientific': 'thomasscientific',
    # 'alliedelec': 'alliedelec'
}
